version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: banco_clinica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: caiomello
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  djangoapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
