# Generated by Django 5.2 on 2025-04-27 16:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(choices=[('cardiologista', 'Cardiologista'), ('dentista', 'Dentista'), ('geriatra', 'Geriatra'), ('ginecologista', 'Ginecologista'), ('neurologista', 'Neurologista'), ('ortopedista', 'Ortopedista'), ('pediatra', 'Pediatra')], default='cardiologista', max_length=100)),
                ('crm', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='O CRM deve conter exatamente 6 dígitos numéricos.', regex='^\\d{6}$')])),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='O e-mail deve estar no formato válido.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='O e-mail deve estar no formato válido.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')])),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressao_arterial', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('muito alta', 'Muito Alta')], default='normal', max_length=20)),
                ('nivel_atividade', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('intensa', 'Intensa')], default='leve', max_length=20)),
                ('data_avaliacao', models.DateField()),
                ('data_retorno', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='clinica.paciente')),
            ],
        ),
    ]
